version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/airba
      - SECRET_KEY=your_secret_key
      - JWT_SECRET_KEY=your_jwt_secret_key
      - LIMIT_IMPORT=true  # Для тестирования ограничим импорт
      - LIMIT_ROWS=100000  # Ограничим до 100 тысяч строк
    networks:
      - app-network
    command: >
      sh -c "python -c 'import time; time.sleep(5)' &&
             python run.py"

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airba
    ports:
      - "5445:5432"  # Исправлено: внешний порт 5445 мапится на внутренний 5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: